package com.model.base;

import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysLog<M extends BaseSysLog<M>> extends BaseModel<M> implements IBean {
	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	public java.lang.Long getId() {
		return getLong("id");
	}
	public M setClassStr(java.lang.String classStr) {
		set("classStr", classStr);
		return (M)this;
	}
	public java.lang.String getClassStr() {
		return getStr("classStr");
	}
	public M setMethodStr(java.lang.String methodStr) {
		set("methodStr", methodStr);
		return (M)this;
	}
	public java.lang.String getMethodStr() {
		return getStr("methodStr");
	}
	public M setLineNumber(java.lang.String lineNumber) {
		set("lineNumber", lineNumber);
		return (M)this;
	}
	public java.lang.String getLineNumber() {
		return getStr("lineNumber");
	}
	public M setCreteTime(java.util.Date creteTime) {
		set("creteTime", creteTime);
		return (M)this;
	}
	public java.util.Date getCreteTime() {
		return get("creteTime");
	}
	public M setLogLevel(java.lang.String logLevel) {
		set("logLevel", logLevel);
		return (M)this;
	}
	public java.lang.String getLogLevel() {
		return getStr("logLevel");
	}
	public M setMsg(java.lang.String msg) {
		set("msg", msg);
		return (M)this;
	}
	public java.lang.String getMsg() {
		return getStr("msg");
	}
}
