package com.model.base;

import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUser<M extends BaseUser<M>> extends BaseModel<M> implements IBean {
	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	public java.lang.Long getId() {
		return getLong("id");
	}
	public M setLoginName(java.lang.String loginName) {
		set("login_name", loginName);
		return (M)this;
	}
	public java.lang.String getLoginName() {
		return getStr("login_name");
	}
	public M setLoginPwd(java.lang.String loginPwd) {
		set("login_pwd", loginPwd);
		return (M)this;
	}
	public java.lang.String getLoginPwd() {
		return getStr("login_pwd");
	}
	public M setUserName(java.lang.String userName) {
		set("user_name", userName);
		return (M)this;
	}
	public java.lang.String getUserName() {
		return getStr("user_name");
	}
	public M setUserIcon(java.lang.String userIcon) {
		set("user_icon", userIcon);
		return (M)this;
	}
	public java.lang.String getUserIcon() {
		return getStr("user_icon");
	}
	public M setUserState(java.lang.Integer userState) {
		set("user_state", userState);
		return (M)this;
	}
	public java.lang.Integer getUserState() {
		return getInt("user_state");
	}
	public M setUserCreateTime(java.util.Date userCreateTime) {
		set("user_create_time", userCreateTime);
		return (M)this;
	}
	public java.util.Date getUserCreateTime() {
		return get("user_create_time");
	}
	public M setLastLoginTime(java.util.Date lastLoginTime) {
		set("last_login_time", lastLoginTime);
		return (M)this;
	}
	public java.util.Date getLastLoginTime() {
		return get("last_login_time");
	}
}
