package com.model;

import com.model.base.BaseSysSql;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysSql extends BaseSysSql<SysSql> {
	public static final SysSql dao = new SysSql().dao();
}
