package com.model;

import com.model.base.BaseTBlog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TBlog extends BaseTBlog<TBlog> {
	public static final TBlog dao = new TBlog().dao();
}
